c3p0:
  jdbcUrl: jdbc:mysql://localhost:3306/discuzq?serverTimeZone=Asia/Shanghai
  user: root
  password: root
  driverClass: com.mysql.cj.jdbc.Driver
  minPoolSize: 1
  maxPoolSize: 5
  maxIdleTime: 3000
  initalPoolSize: 1