spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mbdb?serverTimeZone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
