spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/discuzq?serverTimeZone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20 # 数据库连接池最大值
      initial-size: 5 # 数据库连接池初始值
      min-idle: 5 # 数据库连接池最小空闲值
      min-evictable-idle-time-millis: 300000 # 池中空闲连接大于minIdle且连接空闲时间大于该值，则关闭该连接，单位毫秒(5分钟，默认30分钟)
      max-wait: 60000 # 获取连接时最大等待时间，单位毫秒(1分钟)
      validation-query: select 1 # 获取连接时最大等待时间，单位毫秒(1分钟)
      time-between-eviction-runs-millis: 60000  # 获取连接时最大等待时间，单位毫秒(1分钟)
      filters: stat,wall # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 500
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true #是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        url-pattern: /druid/* #内置的监控页面地址，例如 /druid/*，则内置监控页面的首页是 /druid/index.html
        reset-enable: false # 是否允许清空统计数据
        login-username: admin
        login-password: admin
